// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-rFs-_Hy6lsmG5t62DFfzPG8D6B_7yE',
    appId: '1:436802777007:web:3fb38539b46e3cb131495a',
    messagingSenderId: '436802777007',
    projectId: 'authentication-21d91',
    authDomain: 'authentication-21d91.firebaseapp.com',
    databaseURL: 'https://authentication-21d91-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-21d91.appspot.com',
    measurementId: 'G-FWP80L8NTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSNpwnwNVLl8oulrWj6cXreaWnb2vfHZM',
    appId: '1:436802777007:android:f794fa3806fd824031495a',
    messagingSenderId: '436802777007',
    projectId: 'authentication-21d91',
    databaseURL: 'https://authentication-21d91-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-21d91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoKSp216JnrraEFuvZ3BLw4BV5dVNB7Y4',
    appId: '1:436802777007:ios:cc77da3e7aa49a1331495a',
    messagingSenderId: '436802777007',
    projectId: 'authentication-21d91',
    databaseURL: 'https://authentication-21d91-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-21d91.appspot.com',
    iosBundleId: 'com.example.tabnavigationbar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoKSp216JnrraEFuvZ3BLw4BV5dVNB7Y4',
    appId: '1:436802777007:ios:ab1c5b3a0f0995fe31495a',
    messagingSenderId: '436802777007',
    projectId: 'authentication-21d91',
    databaseURL: 'https://authentication-21d91-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-21d91.appspot.com',
    iosBundleId: 'com.example.tabnavigationbar.RunnerTests',
  );
}
